all: true
mock-build-tags: "test"
with-expecter: true
inpackage: true
recursive: true

packages:
  nil/nil/client: {}
  nil/internal/db: {}
  nil/internal/vm: {}
  nil/services/rollup: {}

include-regex: '^(Client|DB|RwTx|StateDBReadOnly|L1BlockFetcher)$'
