packages:
  - 'smart-contracts'
  - 'niljs'
  - "create-nil-hardhat-project"
  - "docs"
  - "explorer_frontend"
  - "explorer_backend"
  - "uniswap"
  - "clijs"
  - "wallet-extension"
  - "docs_ai_backend"
  - "rollup-bridge-contracts"
  - "academy/lending-protocol"
