// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

import "@nilfoundation/smart-contracts/contracts/Nil.sol";

// In order to handle external transactions (i.e. generated by physical user)
// Smart contract needs to implement `verifyExternal` method
// This functionality may be useful in any case where the contract being called
// Wants to pay for the execution of user request

// Contract `ExternallyAccessible` can be accessed from outside of the system
// It exposes `doSth` method which can be called with appropriately signed transaction
// It's important to notice that the method can only be called with external transaction
// Because of `onlyExternal` modifier

// read more:
// https://docs.nil.foundation/nil/key-principles/account-abstraction
// https://docs.nil.foundation/nil/smart-contracts/receiving-ext-transactions
// https://docs.nil.foundation/nil/smart-contracts/func-modifiers/#onlyinternal-and-onlyexternal
// https://docs.nil.foundation/nil/nilcli/error-handling/#external-transaction-verification-failed

// ExternallyAccessible is a simple stateful contract which keeps user's public key
// The key then used to authorize external transactions sent to the contract by the user

contract ExternallyAccessible is NilBase { // inherit NilBase to have `onlyExternal` modifier
    bytes pubkey;

    constructor(bytes memory _pubkey) payable {
        pubkey = _pubkey;
    }

    function verifyExternal(uint256 hash, bytes calldata signature) external view returns (bool) {
        return Nil.validateSignature(
            pubkey, // public key stored in the contract during creation
            hash, // hash of the external transaction data
            signature // signature for the transaction generated with user private key
        );
    }

    // Dummy function which can only be called with external transaction
    function doSth(uint256 data) onlyExternal pure returns (bool) {
        return data == 0;
    }
}
