# This file contains runtime configuration settings that are used by the explorer frontend.
# All values from this files are going to be loaded as environment variables.
# Treat this file as a standard .env file which values can be changed at runtime.

DOCUMENTATION_URL = "https://docs.nil.foundation/nil/intro"
GITHUB_URL = "https://github.com/NilFoundation/nil-hardhat-example"
API_URL = ""
COMETA_SERVICE_API_URL = ""
HOTJAR_ID = "3726054"
HOTJAR_VERSION = "6"
SANDBOX_DOCS_URL = "https://docs.nil.foundation"
SANDBOX_NILJS_URL = "https://github.com/NilFoundation/nil.js"
SANDBOX_MULTICURRENCY_URL = "https://docs.nil.foundation/nil/getting-started/essentials/tokens-multi-currency"
EXPLORER_USAGE_DOCS_URL = "https://docs.nil.foundation/nil/tools/block-explorer/usage/"
SANDBOX_SUPPORT_URL = "https://t.me/+PT-6HyWK_LBmMmIx"
SANDBOX_FEEDBACK_URL = "https://form.typeform.com/to/pDEAcSqd"
