// Code generated by fastssz. DO NOT EDIT.
// Hash: 16b1f475494e74c443785d17071be9f60381a157d32778336916678cbe3e6981
// Version: 0.1.3
package types

import (
	ssz "github.com/NilFoundation/fastssz"
)

// MarshalSSZ ssz marshals the Message object
func (m *Message) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(m)
}

// MarshalSSZTo ssz marshals the Message object to a target array
func (m *Message) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(154)

	// Field (0) 'Internal'
	dst = ssz.MarshalBool(dst, m.Internal)

	// Field (1) 'Deploy'
	dst = ssz.MarshalBool(dst, m.Deploy)

	// Field (2) 'Seqno'
	dst = ssz.MarshalUint64(dst, uint64(m.Seqno))

	// Field (3) 'GasPrice'
	if dst, err = m.GasPrice.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'GasLimit'
	if dst, err = m.GasLimit.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (5) 'From'
	dst = append(dst, m.From[:]...)

	// Field (6) 'To'
	dst = append(dst, m.To[:]...)

	// Field (7) 'Value'
	if dst, err = m.Value.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (8) 'Data'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(m.Data)

	// Offset (9) 'Signature'
	dst = ssz.WriteOffset(dst, offset)

	// Field (8) 'Data'
	if size := len(m.Data); size > 24576 {
		err = ssz.ErrBytesLengthFn("Message.Data", size, 24576)
		return
	}
	dst = append(dst, m.Data...)

	// Field (9) 'Signature'
	if size := len(m.Signature); size > 256 {
		err = ssz.ErrBytesLengthFn("Message.Signature", size, 256)
		return
	}
	dst = append(dst, m.Signature...)

	return
}

// UnmarshalSSZ ssz unmarshals the Message object
func (m *Message) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 154 {
		return ssz.ErrSize
	}

	tail := buf
	var o8, o9 uint64

	// Field (0) 'Internal'
	m.Internal = ssz.UnmarshalBool(buf[0:1])

	// Field (1) 'Deploy'
	m.Deploy = ssz.UnmarshalBool(buf[1:2])

	// Field (2) 'Seqno'
	m.Seqno = Seqno(ssz.UnmarshallUint64(buf[2:10]))

	// Field (3) 'GasPrice'
	if err = m.GasPrice.UnmarshalSSZ(buf[10:42]); err != nil {
		return err
	}

	// Field (4) 'GasLimit'
	if err = m.GasLimit.UnmarshalSSZ(buf[42:74]); err != nil {
		return err
	}

	// Field (5) 'From'
	copy(m.From[:], buf[74:94])

	// Field (6) 'To'
	copy(m.To[:], buf[94:114])

	// Field (7) 'Value'
	if err = m.Value.UnmarshalSSZ(buf[114:146]); err != nil {
		return err
	}

	// Offset (8) 'Data'
	if o8 = ssz.ReadOffset(buf[146:150]); o8 > size {
		return ssz.ErrOffset
	}

	if o8 < 154 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (9) 'Signature'
	if o9 = ssz.ReadOffset(buf[150:154]); o9 > size || o8 > o9 {
		return ssz.ErrOffset
	}

	// Field (8) 'Data'
	{
		buf = tail[o8:o9]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(m.Data) == 0 {
			m.Data = make([]byte, 0, len(buf))
		}
		m.Data = append(m.Data, buf...)
	}

	// Field (9) 'Signature'
	{
		buf = tail[o9:]
		if len(buf) > 256 {
			return ssz.ErrBytesLength
		}
		if cap(m.Signature) == 0 {
			m.Signature = make([]byte, 0, len(buf))
		}
		m.Signature = append(m.Signature, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Message object
func (m *Message) SizeSSZ() (size int) {
	size = 154

	// Field (8) 'Data'
	size += len(m.Data)

	// Field (9) 'Signature'
	size += len(m.Signature)

	return
}

// HashTreeRoot ssz hashes the Message object
func (m *Message) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(m)
}

// HashTreeRootWith ssz hashes the Message object with a hasher
func (m *Message) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Internal'
	hh.PutBool(m.Internal)

	// Field (1) 'Deploy'
	hh.PutBool(m.Deploy)

	// Field (2) 'Seqno'
	hh.PutUint64(uint64(m.Seqno))

	// Field (3) 'GasPrice'
	if err = m.GasPrice.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'GasLimit'
	if err = m.GasLimit.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'From'
	hh.PutBytes(m.From[:])

	// Field (6) 'To'
	hh.PutBytes(m.To[:])

	// Field (7) 'Value'
	if err = m.Value.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (8) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(m.Data))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(m.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	// Field (9) 'Signature'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(m.Signature))
		if byteLen > 256 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(m.Signature)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (256+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Message object
func (m *Message) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(m)
}

// MarshalSSZ ssz marshals the messageDigest object
func (m *messageDigest) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(m)
}

// MarshalSSZTo ssz marshals the messageDigest object to a target array
func (m *messageDigest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(150)

	// Field (0) 'Internal'
	dst = ssz.MarshalBool(dst, m.Internal)

	// Field (1) 'Deploy'
	dst = ssz.MarshalBool(dst, m.Deploy)

	// Field (2) 'Seqno'
	dst = ssz.MarshalUint64(dst, uint64(m.Seqno))

	// Field (3) 'GasPrice'
	if dst, err = m.GasPrice.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'GasLimit'
	if dst, err = m.GasLimit.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (5) 'From'
	dst = append(dst, m.From[:]...)

	// Field (6) 'To'
	dst = append(dst, m.To[:]...)

	// Field (7) 'Value'
	if dst, err = m.Value.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (8) 'Data'
	dst = ssz.WriteOffset(dst, offset)

	// Field (8) 'Data'
	if size := len(m.Data); size > 24576 {
		err = ssz.ErrBytesLengthFn("messageDigest.Data", size, 24576)
		return
	}
	dst = append(dst, m.Data...)

	return
}

// UnmarshalSSZ ssz unmarshals the messageDigest object
func (m *messageDigest) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 150 {
		return ssz.ErrSize
	}

	tail := buf
	var o8 uint64

	// Field (0) 'Internal'
	m.Internal = ssz.UnmarshalBool(buf[0:1])

	// Field (1) 'Deploy'
	m.Deploy = ssz.UnmarshalBool(buf[1:2])

	// Field (2) 'Seqno'
	m.Seqno = Seqno(ssz.UnmarshallUint64(buf[2:10]))

	// Field (3) 'GasPrice'
	if err = m.GasPrice.UnmarshalSSZ(buf[10:42]); err != nil {
		return err
	}

	// Field (4) 'GasLimit'
	if err = m.GasLimit.UnmarshalSSZ(buf[42:74]); err != nil {
		return err
	}

	// Field (5) 'From'
	copy(m.From[:], buf[74:94])

	// Field (6) 'To'
	copy(m.To[:], buf[94:114])

	// Field (7) 'Value'
	if err = m.Value.UnmarshalSSZ(buf[114:146]); err != nil {
		return err
	}

	// Offset (8) 'Data'
	if o8 = ssz.ReadOffset(buf[146:150]); o8 > size {
		return ssz.ErrOffset
	}

	if o8 < 150 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (8) 'Data'
	{
		buf = tail[o8:]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(m.Data) == 0 {
			m.Data = make([]byte, 0, len(buf))
		}
		m.Data = append(m.Data, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the messageDigest object
func (m *messageDigest) SizeSSZ() (size int) {
	size = 150

	// Field (8) 'Data'
	size += len(m.Data)

	return
}

// HashTreeRoot ssz hashes the messageDigest object
func (m *messageDigest) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(m)
}

// HashTreeRootWith ssz hashes the messageDigest object with a hasher
func (m *messageDigest) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Internal'
	hh.PutBool(m.Internal)

	// Field (1) 'Deploy'
	hh.PutBool(m.Deploy)

	// Field (2) 'Seqno'
	hh.PutUint64(uint64(m.Seqno))

	// Field (3) 'GasPrice'
	if err = m.GasPrice.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'GasLimit'
	if err = m.GasLimit.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'From'
	hh.PutBytes(m.From[:])

	// Field (6) 'To'
	hh.PutBytes(m.To[:])

	// Field (7) 'Value'
	if err = m.Value.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (8) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(m.Data))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(m.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the messageDigest object
func (m *messageDigest) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(m)
}
