// Code generated by fastssz. DO NOT EDIT.
// Hash: 3f9d6f137f69d1cc85dd39a2276c87acef647ce52c990813a0746ff61ebff549
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the DeployMessage object
func (d *DeployMessage) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(d)
}

// MarshalSSZTo ssz marshals the DeployMessage object to a target array
func (d *DeployMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(24)

	// Field (0) 'ShardId'
	dst = ssz.MarshalUint32(dst, d.ShardId)

	// Field (1) 'Seqno'
	dst = ssz.MarshalUint64(dst, d.Seqno)

	// Offset (2) 'PublicKey'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(d.PublicKey)

	// Offset (3) 'Data'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(d.Data)

	// Offset (4) 'Code'
	dst = ssz.WriteOffset(dst, offset)

	// Field (2) 'PublicKey'
	if size := len(d.PublicKey); size > 33 {
		err = ssz.ErrBytesLengthFn("DeployMessage.PublicKey", size, 33)
		return
	}
	dst = append(dst, d.PublicKey...)

	// Field (3) 'Data'
	if size := len(d.Data); size > 24576 {
		err = ssz.ErrBytesLengthFn("DeployMessage.Data", size, 24576)
		return
	}
	dst = append(dst, d.Data...)

	// Field (4) 'Code'
	if size := len(d.Code); size > 24576 {
		err = ssz.ErrBytesLengthFn("DeployMessage.Code", size, 24576)
		return
	}
	dst = append(dst, d.Code...)

	return
}

// UnmarshalSSZ ssz unmarshals the DeployMessage object
func (d *DeployMessage) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 24 {
		return ssz.ErrSize
	}

	tail := buf
	var o2, o3, o4 uint64

	// Field (0) 'ShardId'
	d.ShardId = ssz.UnmarshallUint32(buf[0:4])

	// Field (1) 'Seqno'
	d.Seqno = ssz.UnmarshallUint64(buf[4:12])

	// Offset (2) 'PublicKey'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size {
		return ssz.ErrOffset
	}

	if o2 < 24 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (3) 'Data'
	if o3 = ssz.ReadOffset(buf[16:20]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Offset (4) 'Code'
	if o4 = ssz.ReadOffset(buf[20:24]); o4 > size || o3 > o4 {
		return ssz.ErrOffset
	}

	// Field (2) 'PublicKey'
	{
		buf = tail[o2:o3]
		if len(buf) > 33 {
			return ssz.ErrBytesLength
		}
		if cap(d.PublicKey) == 0 {
			d.PublicKey = make([]byte, 0, len(buf))
		}
		d.PublicKey = append(d.PublicKey, buf...)
	}

	// Field (3) 'Data'
	{
		buf = tail[o3:o4]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(d.Data) == 0 {
			d.Data = make([]byte, 0, len(buf))
		}
		d.Data = append(d.Data, buf...)
	}

	// Field (4) 'Code'
	{
		buf = tail[o4:]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(d.Code) == 0 {
			d.Code = make([]byte, 0, len(buf))
		}
		d.Code = append(d.Code, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the DeployMessage object
func (d *DeployMessage) SizeSSZ() (size int) {
	size = 24

	// Field (2) 'PublicKey'
	size += len(d.PublicKey)

	// Field (3) 'Data'
	size += len(d.Data)

	// Field (4) 'Code'
	size += len(d.Code)

	return
}

// HashTreeRoot ssz hashes the DeployMessage object
func (d *DeployMessage) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(d)
}

// HashTreeRootWith ssz hashes the DeployMessage object with a hasher
func (d *DeployMessage) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ShardId'
	hh.PutUint32(d.ShardId)

	// Field (1) 'Seqno'
	hh.PutUint64(d.Seqno)

	// Field (2) 'PublicKey'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(d.PublicKey))
		if byteLen > 33 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(d.PublicKey)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (33+31)/32)
	}

	// Field (3) 'Data'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(d.Data))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(d.Data)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	// Field (4) 'Code'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(d.Code))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(d.Code)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the DeployMessage object
func (d *DeployMessage) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(d)
}
