// Code generated by fastssz. DO NOT EDIT.
// Hash: 0acf786e681fa5c62cb4b3a24c50ff00ba02caf1ced9544a7400723b5f49d90f
// Version: 0.1.3
package types

import (
	ssz "github.com/NilFoundation/fastssz"
)

// MarshalSSZ ssz marshals the DeployMessage object
func (d *DeployMessage) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(d)
}

// MarshalSSZTo ssz marshals the DeployMessage object to a target array
func (d *DeployMessage) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(16)

	// Field (0) 'ShardId'
	dst = ssz.MarshalUint32(dst, uint32(d.ShardId))

	// Field (1) 'Seqno'
	dst = ssz.MarshalUint64(dst, uint64(d.Seqno))

	// Offset (2) 'Code'
	dst = ssz.WriteOffset(dst, offset)

	// Field (2) 'Code'
	if size := len(d.Code); size > 24576 {
		err = ssz.ErrBytesLengthFn("DeployMessage.Code", size, 24576)
		return
	}
	dst = append(dst, d.Code...)

	return
}

// UnmarshalSSZ ssz unmarshals the DeployMessage object
func (d *DeployMessage) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 16 {
		return ssz.ErrSize
	}

	tail := buf
	var o2 uint64

	// Field (0) 'ShardId'
	d.ShardId = ShardId(ssz.UnmarshallUint32(buf[0:4]))

	// Field (1) 'Seqno'
	d.Seqno = Seqno(ssz.UnmarshallUint64(buf[4:12]))

	// Offset (2) 'Code'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size {
		return ssz.ErrOffset
	}

	if o2 < 16 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (2) 'Code'
	{
		buf = tail[o2:]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(d.Code) == 0 {
			d.Code = make([]byte, 0, len(buf))
		}
		d.Code = append(d.Code, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the DeployMessage object
func (d *DeployMessage) SizeSSZ() (size int) {
	size = 16

	// Field (2) 'Code'
	size += len(d.Code)

	return
}

// HashTreeRoot ssz hashes the DeployMessage object
func (d *DeployMessage) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(d)
}

// HashTreeRootWith ssz hashes the DeployMessage object with a hasher
func (d *DeployMessage) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ShardId'
	hh.PutUint32(uint32(d.ShardId))

	// Field (1) 'Seqno'
	hh.PutUint64(uint64(d.Seqno))

	// Field (2) 'Code'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(d.Code))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(d.Code)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the DeployMessage object
func (d *DeployMessage) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(d)
}

// MarshalSSZ ssz marshals the AddressSourceData object
func (a *AddressSourceData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AddressSourceData object to a target array
func (a *AddressSourceData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(24)

	// Field (0) 'ShardId'
	dst = ssz.MarshalUint32(dst, uint32(a.ShardId))

	// Field (1) 'Seqno'
	dst = ssz.MarshalUint64(dst, uint64(a.Seqno))

	// Offset (2) 'Code'
	dst = ssz.WriteOffset(dst, offset)

	// Field (3) 'Salt'
	dst = ssz.MarshalUint64(dst, a.Salt)

	// Field (2) 'Code'
	if size := len(a.Code); size > 24576 {
		err = ssz.ErrBytesLengthFn("AddressSourceData.Code", size, 24576)
		return
	}
	dst = append(dst, a.Code...)

	return
}

// UnmarshalSSZ ssz unmarshals the AddressSourceData object
func (a *AddressSourceData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 24 {
		return ssz.ErrSize
	}

	tail := buf
	var o2 uint64

	// Field (0) 'ShardId'
	a.ShardId = ShardId(ssz.UnmarshallUint32(buf[0:4]))

	// Field (1) 'Seqno'
	a.Seqno = Seqno(ssz.UnmarshallUint64(buf[4:12]))

	// Offset (2) 'Code'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size {
		return ssz.ErrOffset
	}

	if o2 < 24 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (3) 'Salt'
	a.Salt = ssz.UnmarshallUint64(buf[16:24])

	// Field (2) 'Code'
	{
		buf = tail[o2:]
		if len(buf) > 24576 {
			return ssz.ErrBytesLength
		}
		if cap(a.Code) == 0 {
			a.Code = make([]byte, 0, len(buf))
		}
		a.Code = append(a.Code, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AddressSourceData object
func (a *AddressSourceData) SizeSSZ() (size int) {
	size = 24

	// Field (2) 'Code'
	size += len(a.Code)

	return
}

// HashTreeRoot ssz hashes the AddressSourceData object
func (a *AddressSourceData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AddressSourceData object with a hasher
func (a *AddressSourceData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ShardId'
	hh.PutUint32(uint32(a.ShardId))

	// Field (1) 'Seqno'
	hh.PutUint64(uint64(a.Seqno))

	// Field (2) 'Code'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(a.Code))
		if byteLen > 24576 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(a.Code)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (24576+31)/32)
	}

	// Field (3) 'Salt'
	hh.PutUint64(a.Salt)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AddressSourceData object
func (a *AddressSourceData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
