// Code generated by mockery v2.53.3. DO NOT EDIT.

//go:build test

package rollup

import (
	context "context"

	types "github.com/ethereum/go-ethereum/core/types"
	mock "github.com/stretchr/testify/mock"
)

// MockL1BlockFetcher is an autogenerated mock type for the L1BlockFetcher type
type MockL1BlockFetcher struct {
	mock.Mock
}

type MockL1BlockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockL1BlockFetcher) EXPECT() *MockL1BlockFetcher_Expecter {
	return &MockL1BlockFetcher_Expecter{mock: &_m.Mock}
}

// GetLastBlockInfo provides a mock function with given fields: ctx
func (_m *MockL1BlockFetcher) GetLastBlockInfo(ctx context.Context) (*types.Header, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastBlockInfo")
	}

	var r0 *types.Header
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*types.Header, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *types.Header); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Header)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockL1BlockFetcher_GetLastBlockInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastBlockInfo'
type MockL1BlockFetcher_GetLastBlockInfo_Call struct {
	*mock.Call
}

// GetLastBlockInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockL1BlockFetcher_Expecter) GetLastBlockInfo(ctx interface{}) *MockL1BlockFetcher_GetLastBlockInfo_Call {
	return &MockL1BlockFetcher_GetLastBlockInfo_Call{Call: _e.mock.On("GetLastBlockInfo", ctx)}
}

func (_c *MockL1BlockFetcher_GetLastBlockInfo_Call) Run(run func(ctx context.Context)) *MockL1BlockFetcher_GetLastBlockInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockL1BlockFetcher_GetLastBlockInfo_Call) Return(_a0 *types.Header, _a1 error) *MockL1BlockFetcher_GetLastBlockInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockL1BlockFetcher_GetLastBlockInfo_Call) RunAndReturn(run func(context.Context) (*types.Header, error)) *MockL1BlockFetcher_GetLastBlockInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockL1BlockFetcher creates a new instance of MockL1BlockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockL1BlockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockL1BlockFetcher {
	mock := &MockL1BlockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
