// Code generated by "stringer -type=TaskErrType -trimprefix=TaskErr -output=taskerrtype_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskErrTimeout-1]
	_ = x[TaskErrRpc-2]
	_ = x[TaskErrIO-3]
	_ = x[TaskErrInvalidTask-4]
	_ = x[TaskErrInvalidInputData-5]
	_ = x[TaskErrProofGenerationFailed-6]
	_ = x[TaskErrTerminated-7]
	_ = x[TaskErrNotSupportedType-8]
	_ = x[TaskErrOutOfMemory-9]
	_ = x[TaskErrCancelled-10]
	_ = x[TaskErrUnknown-11]
}

const _TaskErrType_name = "TimeoutRpcIOInvalidTaskInvalidInputDataProofGenerationFailedTerminatedNotSupportedTypeOutOfMemoryCancelledUnknown"

var _TaskErrType_index = [...]uint8{0, 7, 10, 12, 23, 39, 60, 70, 86, 97, 106, 113}

func (i TaskErrType) String() string {
	i -= 1
	if i < 0 || i >= TaskErrType(len(_TaskErrType_index)-1) {
		return "TaskErrType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TaskErrType_name[_TaskErrType_index[i]:_TaskErrType_index[i+1]]
}
