// Code generated by "stringer -type=TaskType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TaskTypeNone-0]
	_ = x[ProofBatch-1]
	_ = x[PartialProve-2]
	_ = x[AggregatedChallenge-3]
	_ = x[CombinedQ-4]
	_ = x[AggregatedFRI-5]
	_ = x[FRIConsistencyChecks-6]
	_ = x[MergeProof-7]
}

const _TaskType_name = "TaskTypeNoneProofBatchPartialProveAggregatedChallengeCombinedQAggregatedFRIFRIConsistencyChecksMergeProof"

var _TaskType_index = [...]uint8{0, 12, 22, 34, 53, 62, 75, 95, 105}

func (i TaskType) String() string {
	if i >= TaskType(len(_TaskType_index)-1) {
		return "TaskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskType_name[_TaskType_index[i]:_TaskType_index[i+1]]
}
