name: Build artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix_check_macos:
    name: macOS
    uses: ./.github/workflows/nix_check_macos.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      upload_artifacts: true

  lint_and_build:
    name: Linux
    uses: ./.github/workflows/lint_and_build.yml
    secrets: inherit
    with:
      upload_artifacts: ${{ github.event_name == 'workflow_dispatch' }}
      upload_packages_to_s3: true
