name: Cluster CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix_check_linux:
    name: Linux
    uses: ./.github/workflows/nix_check_linux.yml

  nix_check_macos:
    name: macOS
    uses: ./.github/workflows/nix_check_macos.yml
    with:
      upload_artifacts: ${{ github.event_name == 'workflow_dispatch' }}

  lint_and_build:
    name: Lint and build
    uses: ./.github/workflows/lint_and_build.yml
    secrets: inherit
    with:
      upload_artifacts: ${{ github.event_name == 'workflow_dispatch' }}
      upload_packages_to_s3: false
