name: Cluster CI (macOS)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ensure_cluster_builds_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: macos-13
            arch: amd64
    environment: prod
    name: MacOS CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v4

      - name: Install Golang and solc
        run: |
          brew tap ethereum/ethereum
          brew install go solidity

      - name: build binaries
        run: make

      - name: Upload binaries as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil-macos-${{ matrix.arch }}-${{ github.run_number }}
          path: |
            build/bin/*
