name: Cluster CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ensure_cluster_builds_linux:
    runs-on: ["self-hosted", "aws_autoscaling"]
    environment: prod
    name: Linux CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: compile contracts
        run: nix develop -c make compile-contracts

      - name: SSZ generation
        run: nix develop -c make ssz

      - name: golangci-lint
        run: nix develop -c golangci-lint run

      - name: run tests with race detector
        run: nix flake check -L

      - name: build
        run: nix build -L

      - name: Generate OpenRPC spec for JSON RPC API
        run: nix develop -c make rpcspec

      - name: Upload nil_cli binary as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil_cli-linux-x64
          path: |
            result/bin/nil_cli

      - name: upload packages to s3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export PATH=/home/ec2-user/.local/bin:${PATH}
          nix bundle --bundler . .#nil -L
          sudo yum update -y
          sudo yum install -y awscli python3-pip
          pip3 install -U mkrepo
          aws s3 cp "deb-package-nil/`ls deb-package-nil`" s3://nil-deb-repo/ubuntu/pool/main/d/nil/
          mkrepo s3://nil-deb-repo/ubuntu

  ensure_cluster_builds_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: macos-13
            arch: x64
    environment: prod
    name: MacOS CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Golang and solc
        run: |
          brew tap ethereum/ethereum
          brew install go solidity

      - name: build binaries
        run: make

      - name: Upload nil_cli binary as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil_cli-darwin-${{ matrix.arch }}
          path: |
            build/bin/nil_cli
