name: Cluster CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ensure_cluster_builds_linux:
    runs-on: ["self-hosted", "aws_autoscaling"]
    environment: prod
    name: Linux CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: compile contracts
        run: nix develop -c make compile-contracts

      - name: golangci-lint
        run: nix develop -c golangci-lint run

      - name: build
        run: nix build -L

      - name: SSZ generation
        run: nix develop -c make ssz

      - name: Generate OpenRPC spec for JSON RPC API
        run: nix develop -c make rpcspec

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nil-linux-amd64-${{ github.run_number }}
          path: |
            build/bin/*

      - name: upload packages to s3
        if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' ||  github.ref == 'refs/heads/master') }}
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export PATH=/home/ec2-user/.local/bin:${PATH}
          nix bundle --bundler . .#nil
          sudo yum update -y
          sudo yum install -y awscli python3-pip
          pip3 install -U mkrepo
          aws s3 cp "deb-package-nil/`ls deb-package-nil`" s3://nil-deb-repo/ubuntu/pool/main/d/nil/
          mkrepo s3://nil-deb-repo/ubuntu
