name: Cluster CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nix_check:
    name: Test - ${{ matrix.check }}
    runs-on: ["self-hosted", "aws_autoscaling"]
    strategy:
      fail-fast: false
      matrix:
        check: ["ibft", "heavy", "nil", "nildocs", "niljs", "nilexplorer", "uniswap", "clijs"]
    steps:
      - name: checkout local actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run check
        run: nix build .#checks.x86_64-linux.${{ matrix.check == 'nil' && 'others' || matrix.check }} -L

  build_artifacts:
    name: Build artifacts
    runs-on: ["self-hosted", "aws_autoscaling"]
    environment: prod
    steps:
      - name: checkout local actions
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run formatters
        run: |
          ./scripts/sh_format_all.sh -n -c
          ./scripts/nix_format_all.sh -n -c

      - name: Generate required go files
        run: nix develop -c make generated

      - name: golangci-lint
        run: nix develop -c golangci-lint run

      - name: build
        run: nix build -L

      - name: Upload nil binary as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil-linux-x64
          path: |
            result/bin/nil

      - name: upload packages to s3
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export PATH=/home/ec2-user/.local/bin:${PATH}
          nix bundle --bundler . .#nil -L
          sudo yum update -y
          sudo yum install -y awscli python3-pip
          pip3 install -U mkrepo
          aws s3 cp "deb-package-nil/`ls deb-package-nil`" s3://nil-deb-repo/ubuntu/pool/main/d/nil/
          mkrepo s3://nil-deb-repo/ubuntu

  ensure_cluster_builds_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: macos-13
            arch: x64
    environment: prod
    name: MacOS CI
    steps:
      - name: checkout local actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Golang and solc
        run: |
          brew update
          brew tap ethereum/ethereum
          brew install go solidity protobuf coreutils
          go install golang.org/x/tools/cmd/stringer@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: build binaries
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make

      - name: Upload nil binary as artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: nil-darwin-${{ matrix.arch }}
          path: |
            build/bin/nil
